dbt_airflow:
  target: dev

  outputs:
    dev:
      type: bigquery
      method: service-account
      project: dbt-project-508815
      dataset: "{{ env_var('DBT_DBNAME', 'dbt_airflow_dw') }}"
      threads: 4
      keyfile: "{{ env_var('GCP_KEYFILE_PATH') }}"

   
