name: dbt CD

on:
  push:
    branches:
      - main

jobs:
  dbt-delivery:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Prepare production artifact
        run: |
          mkdir -p delivery/.astro

          cp -r dags delivery/
          cp -r dbt_airflow delivery/

          cp Dockerfile delivery/
          cp requirements.txt delivery/
          cp packages.txt delivery/
          cp airflow_settings.yaml delivery/
          cp .astro/config.yaml delivery/.astro/

      - name: Upload production artifact
        uses: actions/upload-artifact@v4
        with:
          name: airflow-dbt-production
          path: delivery

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        run: |
          docker build \
            -t mendesdsilva/airflow-dbt:latest \
            -t mendesdsilva/airflow-dbt:${{ github.sha }} \
            .

      - name: Push Docker image
        run: |
          docker push mendesdsilva/airflow-dbt:latest
          docker push mendesdsilva/airflow-dbt:${{ github.sha }}
